#!/usr/bin/env bash

# --- 1. システム・基本操作 ---
alias sudo='doas'
alias rm='trash-put'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias c='clear'
alias cl='cd && clear'
alias :q='exit'
alias neofetch='fastfetch'

# --- 2. エディタ (Neovim) ---
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias vimdiff='nvim -R -d'
alias cnf='cd ${XDG_CONFIG_HOME:-$HOME/.config}/nvim'

# --- 3. Rust製モダンコマンドへの置換 ---
# eza: lsの代替
alias ls='eza --icons'
alias la='eza --all --icons'
alias ll='eza -hl --git'
alias lla='eza --all -hl --git'
alias lt='eza --tree --icons'
alias lta='eza --all --tree --icons'

# その他ツールの代替
alias cat='bat'
alias grep='rg'
alias find='fd'
alias fzf='sk'

# --- 4. ファイルマネージャ・ツール ---
alias lf='yazi'
alias ranger='yazi'
alias mozc='/usr/lib/mozc/mozc_tool --mode=config_dialog'

# --- 5. 開発・インタラクティブ検索 ---
# ghq + skim
alias fzghq='cd "$(ghq list -p | sk)"'

# ---------------------------------------------------------
# 関数定義 (引数が必要なもの)
# ---------------------------------------------------------

# GitHubからクローン
clone() {
    git clone git@github.com:"$1".git
}

# ghq経由でリポジトリを取得
get() {
    ghq get https://github.com/"$1"
}

# 天気表示 (デフォルト: 東京)
wttr() {
    curl -H "Accept-Language: ${LANG%_*}" wttr.in/"${1:-Tokyo}"
}

# ディレクトリ作成後に移動
mkcd() {
    mkdir -p "$1" && cd "$1" || return
}

# URLからQRコードを生成
qrcode() {
    curl qrcode.show/"$1"
}
