#!/usr/bin/env bash
OS="$(uname)"

# --- 1. エディタ・基本アプリの設定 ---
export VISUAL="nvim"
export EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="wezterm"
export TERM="xterm-256color"
export NVIM_APPNAME="nvim"

# --- 2. XDG Base Directory ---
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

# --- 3. 言語・開発ツール環境 ---
# Go
export GOPATH="$HOME/Develop/go"
export GOBIN="$GOPATH/bin"

# Android SDK
if [ "$OS" = "Linux" ]; then
  export ANDROID_HOME="$HOME/Develop/Android/Sdk"
fi

# volta (Node.js)
export VOLTA_HOME="$HOME/.volta"

# --- 4. システム・UI・ツール設定 ---
if [ "$OS" = "Linux" ]; then
  export QT_QPA_PLATFORMTHEME="qt6ct"
  export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
  export GTK_THEME="Matcha-azul:dark"
  export FCITX_CONFIG_DIR="$HOME/.local/share/fcitx5"
fi

export GPG_TTY="$(tty)"
export BAT_THEME="Nord"
export LESS="-R"

# --- 5. PATHの設定 ---
export PATH="$PATH:$GOBIN"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$VOLTA_HOME/bin:$PATH"
export PATH="$PATH:$HOME/.lmstudio/bin"

if [ "$OS" = "Linux" ]; then
  export PATH="$PATH:$ANDROID_HOME/platform-tools/"
  export PATH="$PATH:$ANDROID_HOME/tools/bin/"
  export PATH="$PATH:$ANDROID_HOME/emulator/"
  export PATH="$PATH:$ANDROID_HOME/tools/"
fi

if [ "$OS" = "Darwin" ]; then
  export PATH="/opt/homebrew/opt/trash-cli/bin:$PATH"
fi
