#!/usr/bin/env bash

# vim aliases
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias vimdiff='nvim -R -d'
alias cnf='cd $HOME/.config/nvim'

# rust command
alias ls='exa --icons'
alias la='exa --all --icons'
alias ll='exa -hl --git'
alias lla='exa --all -hl --git'
alias lt='exa --tree --icons'
alias lta='exa --all --tree --icons'
alias cat='bat'
alias yay='paru'
alias grep='rg'
alias find='fd'
alias fzf='sk'

# aliases
alias lf='lfrun'
alias ranger='lfrun'
alias rm='trash-put'
alias cp='cp -i'
alias mv='mv -i'
alias mozc='/usr/lib/mozc/mozc_tool --mode=config_dialog'
alias w3md='w3m duckduckgo.com'
alias w3ma='w3m aur.archlinux.org'
alias c='clear'
alias cl='cd && clear'
alias :q='exit'
alias mkdir='mkdir -p'
alias i3config='nvim $XDG_CONFIG_HOME/i3/config'
alias neofetch='fastfetch'

# skim + ghq
alias fzghq='cd "$(ghq list -p | sk)"'

# git alias
clone() {
	git clone https://github.com/"$1".git
}

# ghq alias
get() {
	ghq get https://github.com/"$1"
}

# get weather
wttr() {
	curl -H "Accept-Language: ${LANG%_*}" wttr.in/"${1:-Tokyo}"
}

# mkdir and cd
mkcd() {
	mkdir -p "$1" && cd "$1" || return
}

# create qrcode from url
qrcode() {
	curl qrcode.show/"$1"
}
