[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_event = ['InsertEnter', 'CursorHold']
on_source = 'nvim-lspconfig'
lua_source = '''
  local cmp = require('cmp')
  local keymap = require('cmp.utils.keymap')
  local cmp_autopairs = require('nvim-autopairs.completion.cmp')
  local lspkind = require('lspkind')

  cmp.setup({
    snippet = {
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
      end,
    },
    window = {
      documentation = cmp.config.window.bordered(),
    },
    mapping = cmp.mapping.preset.insert({
      ['<C-u>'] = cmp.mapping.scroll_docs(-4),
      ['<C-d>'] = cmp.mapping.scroll_docs(4),
      ['<C-c>'] = cmp.mapping.abort(),
      ['<C-e>'] = cmp.mapping(function()
        vim.api.nvim_feedkeys(keymap.t('<End>'), 'i', false)
      end),
      ['<CR>'] = cmp.mapping.confirm({ select = true }),
    }),
    sources = cmp.config.sources({
      { name = 'nvim_lsp' },
      { name = 'vsnip' },
      { name = 'buffer' },
      { name = 'tmux' },
      { name = 'path' },
      { name = 'skkeleton' },
    }),
    formatting = {
      format = lspkind.cmp_format({
        mode = "symbol",
        maxwidth = 50,
        menu = ({
          nvim_lsp = "[LSP]",
          vsnip = "[vsnip]",
          buffer = "[buffer]",
          path = "[path]",
          cmdline = "[cmdline]",
          cmdline_history = "[history]",
        })
      })
    },
  })

  cmp.setup.filetype({ 'NeogitCommitMessage', 'gitcommit', 'markdown' }, {
    sources = cmp.config.sources({
      { name = 'mocword' },
      { name = 'path' },
      { name = 'skkeleton' },
    })
  })

  cmp.setup.filetype({ 'toml' }, {
    sources = cmp.config.sources({
      { name = 'vsnip' },
      { name = 'buffer' },
      { name = 'tmux' },
      { name = 'mocword' },
      { name = 'skkeleton' },
    })
  })

  cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = cmp.config.sources({
      { name = 'cmdline' },
      { name = 'cmdline_history' },
      { name = 'path' }
    })
  })

  cmp.event:on(
    'confirm_done',
    cmp_autopairs.on_confirm_done()
  )
'''

# cmp sources
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = ['nvim-cmp', 'nvim-lspconfig']

[[plugins]]
repo = 'yutkat/cmp-mocword'
depends = ['plenary.nvim']
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'dmitmel/cmp-cmdline-history'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'andersevenrud/cmp-tmux'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'rinx/cmp-skkeleton'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'onsails/lspkind.nvim'
on_source = 'nvim-cmp'

# snippet
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = 'nvim-cmp'
hook_add = '''
  let g:vsnip_snippet_dir = '$HOME/.config/nvim/vsnip'
  imap <expr> <Tab>   vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<Tab>'
  smap <expr> <Tab>   vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<Tab>'
  imap <expr> <S-Tab> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-Tab>'
  smap <expr> <S-Tab> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-Tab>'
'''

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = 'nvim-cmp'

# autopairs
[[plugins]]
repo = 'windwp/nvim-autopairs'
on_source = 'nvim-cmp'
lua_source = '''
  local npairs = require'nvim-autopairs'
  local Rule = require'nvim-autopairs.rule'
  local brackets = { { '(', ')' }, { '[', ']' }, { '{', '}' } }

  npairs.setup()
  npairs.add_rules {
    Rule(' ', ' ')
      :with_pair(function (opts)
        local pair = opts.line:sub(opts.col - 1, opts.col)
        return vim.tbl_contains({
          brackets[1][1]..brackets[1][2],
          brackets[2][1]..brackets[2][2],
          brackets[3][1]..brackets[3][2],
        }, pair)
      end)
  }
  for _,bracket in pairs(brackets) do
    npairs.add_rules {
      Rule(bracket[1]..' ', ' '..bracket[2])
        :with_pair(function() return false end)
        :with_move(function(opts)
          return opts.prev_char:match('.%'..bracket[2]) ~= nil
        end)
        :use_key(bracket[2])
    }
  end
'''

