[[plugins]]
repo = 'lambdalisue/fern.vim'
on_cmd = 'Fern'
hook_add = '''
  nnoremap <silent> sf <Cmd>Fern .<CR>
  nnoremap <silent> <Space>f <Cmd>Fern . -reveal=% -drawer -toggle -width=40<CR>
'''
[plugins.ftplugin]
fern = '''
  nmap <buffer><silent> y <Plug>(fern-action-clipboard-copy)
  nmap <buffer><silent> m <Plug>(fern-action-clipboard-move)
  nmap <buffer><silent> P <Plug>(fern-action-clipboard-paste)
  nmap <buffer><silent> D <Plug>(fern-action-remove)
  nmap <buffer><silent> <Del> <Plug>(fern-action-remove)
  nmap <buffer><silent> r <Plug>(fern-action-rename:bottom)
  nmap <buffer><silent> x <Plug>(fern-action-mark)<Down>
  nnoremap <buffer><silent> q <Cmd>Fern . -reveal=% -drawer -toggle -width=40<CR>
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = 'fern.vim'
hook_post_source = '''
  call fern_git_status#init()
'''

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
on_source = 'fern.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
  let g:fern#renderer#nerdfont#indent_markers = 1
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'LumaKernel/fern-mapping-reload-all.vim'
on_source = 'fern.vim'
[plugins.ftplugin]
fern = '''
  nmap <buffer><silent> <C-r> <Plug>(fern-action-reload:all)
'''

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
on_source = 'fern.vim'
[plugins.ftplugin]
fern = '''
  nmap <buffer><silent> p       <Plug>(fern-action-preview:toggle)
  nmap <buffer><silent> <C-n>   <Plug>(fern-action-preview:scroll:down:half)
  nmap <buffer><silent> <C-p>   <Plug>(fern-action-preview:scroll:up:half)
'''
