[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_cmd = 'AsyncRun'
hook_add = '''
  autocmd MyAutoCmd User AsyncRunStart call asyncrun#quickfix_toggle(25, 1)
'''

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_cmd = 'Template'
hook_add = '''
  let g:sonictemplate_vim_template_dir = '$HOME/.config/nvim/template'
'''

[[plugins]]
repo = 'segeljakt/vim-silicon'
on_cmd = 'Silicon'
hook_add = '''
  let g:silicon = {
    \ 'theme': 'Nord',
    \ 'font': 'SauceCodePro Nerd Font',
    \ 'output': '~/Pictures/silicon/silicon-{time:%Y-%m-%d-%H:%M:%S}.png',
    \ }
'''

[[plugins]]
repo = 'dstein64/vim-startuptime'
on_cmd = 'StartupTime'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = ['OpenBrowser', 'OpenBrowserSearch']
on_map = ['<Plug>(openbrowser-']
hook_add = '''
  let g:openbrowser_default_search = 'duckduckgo'
  let g:openbrowser_message_verbosity = 0

  nmap <Space>i <Plug>(openbrowser-smart-search)
  vmap <Space>i <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'utubo/vim-auto-hide-cmdline'
