[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['plenary.nvim', 'nvim-treesitter', 'nvim-web-devicons']
on_cmd = 'Telescope'
on_lua = 'telescope'
hook_add = '''
  command! Cnft lua require('telescope.builtin').find_files({ cwd = vim.fn.expand('~/.config/nvim') })
'''
lua_source = '''
  local actions = require('telescope.actions')
  require('telescope').setup({
    defaults = {
      sorting_strategy = "ascending",
      prompt_prefix = "  ",
      layout_config = {
        horizontal = {
          prompt_position = "top",
          preview_width = 0.55,
          results_width = 0.8,
        },
      },
      mappings = {
        i = {
          ["jj"] = { "<Esc><Right>", type = "command" },
          ["<Esc>"] = actions.close,
          ["<C-j>"] = actions.move_selection_next,
          ["<C-k>"] = actions.move_selection_previous,
          ["<C-n>"] = actions.preview_scrolling_down,
          ["<C-p>"] = actions.preview_scrolling_up,
        },
        n = {
          ["q"] = actions.close,
          ["x"] = actions.toggle_selection,
          ["*"] = actions.toggle_all,
          ["<C-n>"] = actions.preview_scrolling_down,
          ["<C-p>"] = actions.preview_scrolling_up,
        },
      },
    },
    preview = {
      timeout = 3000,
    },
    extensions = {
      fzy_native = {
        override_generic_sorter = false,
        override_file_sorter = true,
      },
      repo = {
        search_dirs = {
          "~/Develop/git/github.com/"
        },
      },
    },
  })
  require('telescope').load_extension('fzy_native')
'''

[[plugins]]
repo = 'nvim-telescope/telescope-fzy-native.nvim'
on_source = 'telescope.nvim'
