[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
lua_source = '''
  local rainbow = { "#E8BA36", "#54A857", "#359FF4", "#5060BB", "#179387", "#88C0D0", "#5E81AC" }
  require'nvim-treesitter.configs'.setup {
    ensure_installed = "all",
    highlight = {
      enable = true,
    },
    yati = {
      enable = true,
      disable = { "cpp" },
    },
    indent = {
      enable = false,
    },
    rainbow = {
      enable = true,
      extended_mode = true,
      max_file_lines = 1000,
      colors = rainbow,
    },
  }
  for i, c in ipairs(rainbow) do
    vim.cmd(("hi rainbowcol%d guifg=%s"):format(i, c))
  end
'''
hook_post_update = '''
  TSUpdate
'''

[[plugins]]
repo = 'mrjones2014/nvim-ts-rainbow'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'yioneko/nvim-yati'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
depends = ['nvim-treesitter']
on_ft = ['html']
lua_source = '''
  require('nvim-ts-autotag').setup()
'''
