#!/bin/bash

PLAYER="spotify"

if [ -n "$BLOCK_BUTTON" ]; then
  case $BLOCK_BUTTON in
    1) playerctl --player=$PLAYER play-pause ;;
	3) i3-msg workspace "5: " > /dev/null ;;
    4) playerctl --player=$PLAYER previous ;;
    5) playerctl --player=$PLAYER next ;;
  esac
fi

# Spotifyが実行されているかチェック
if ! pgrep -x spotify > /dev/null; then
    echo "Spotify is not running"
    exit
fi


# 曲情報を取得して表示
STATUS=$(playerctl --player=$PLAYER status 2>/dev/null)

if [ "$STATUS" = "Playing" ]; then
  playerctl --player=$PLAYER metadata --format '{{ artist }} - {{ title }} '
elif [ "$STATUS" = "Paused" ]; then
  playerctl --player=$PLAYER metadata --format '{{ artist }} - {{ title }} '
else
  echo "Stopped"
fi
