[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = ['CursorHold']
# hook_add = '''
#   let g:denops_server_addr = '127.0.0.1:32123'
#   " let g:denops#debug = 1
#   " command! DenopsRestart call denops#server#restart()
# '''

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'skk-dev/dict'

[[plugins]]
repo = 'vim-skk/skkeleton'
on_source = ['ddc.vim', 'nvim-cmp']
on_map = {ic = '<Plug>(skkeleton-toggle)'}
hook_add = '''
  imap <C-Space> <Plug>(skkeleton-toggle)
  cmap <C-Space> <Plug>(skkeleton-toggle)
'''
hook_source = '''
  " \ 'globalDictionaries': ["/usr/share/skk/SKK-JISYO.L"],
  call skkeleton#config({
    \ 'eggLikeNewline': v:true,
    \ 'globalDictionaries': [
    \   "~/.cache/dein/repos/github.com/skk-dev/dict/SKK-JISYO.L",
    \ ],
    \ })
  call skkeleton#register_kanatable('rom', {
    \ 'jj': 'escape',
    \ ';': 'henkanPoint',
    \ })
'''

[[plugins]]
repo = 'skanehira/denops-translate.vim'
depends = 'denops.vim'
on_map = ['<Plug>(Translate)']
hook_add = '''
  nmap <C-t> <Plug>(Translate)
  vmap <C-t> <Plug>(Translate)
'''

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
depends = ['denops.vim', 'vim-auto-hide-cmdline', 'kensaku.vim']
on_map = ['<Plug>(ahc)']
hook_add = '''
  nmap <Space><Space> <Plug>(ahc)<Cmd>FuzzyMotion<CR>
  let g:fuzzy_motion_matchers = ['fzf', 'kensaku']
'''
