[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufRead', 'BufNewFile']
lua_source = '''
  require("nvim-treesitter.configs").setup {
    ensure_installed = "all",
    highlight = {
      enable = true,
    },
    yati = {
      enable = true,
      disable = { "cpp" },
    },
    indent = {
      enable = false,
    },
    autotag = {
      enable = true,
    },
  }
'''
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'yioneko/nvim-yati'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'HiPhish/rainbow-delimiters.nvim'
on_source = 'nvim-treesitter'
lua_source = '''
  local rainbow_delimiters = require('rainbow-delimiters')

  vim.g.rainbow_delimiters = {
    strategy = {
      [''] = rainbow_delimiters.strategy['global'],
      vim = rainbow_delimiters.strategy['local'],
    },
    query = {
      [''] = 'rainbow-delimiters',
      lua = 'rainbow-blocks',
    },
    highlight = {
      'RainbowDelimiterRed',
      'RainbowDelimiterYellow',
      'RainbowDelimiterBlue',
      'RainbowDelimiterOrange',
      'RainbowDelimiterGreen',
      'RainbowDelimiterViolet',
      'RainbowDelimiterCyan',
    },
  }
  vim.cmd([[
    highlight RainbowDelimiterRed guifg=#E8BA36
    highlight RainbowDelimiterOrange guifg=#54A857
    highlight RainbowDelimiterYellow guifg=#359FF4
    highlight RainbowDelimiterGreen guifg=#5060BB
    highlight RainbowDelimiterCyan guifg=#179387
    highlight RainbowDelimiterBlue guifg=#88C0D0
    highlight RainbowDelimiterViolet guifg=#5E81AC
  ]])
'''
