[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'tjdevries/colorbuddy.nvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja
'''
