[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja
'''

[[plugins]]
repo = 'nathom/filetype.nvim'

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
  colorscheme tokyonight
'''

