[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja
'''

[[plugins]]
repo = 'nathom/filetype.nvim'

[[plugins]]
repo = 'lewis6991/impatient.nvim'
lua_add = '''
  require('impatient')
'''

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
  colorscheme tokyonight
  " let g:tokyonight_style = "night"
'''

