[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = ['CursorHold']

[[plugins]]
repo = 'vim-skk/skkeleton'
on_source = 'ddc.vim'
on_map = {ic = '<Plug>(skkeleton-toggle)'}
hook_add = '''
  imap <C-Space> <Plug>(skkeleton-toggle)
  cmap <C-Space> <Plug>(skkeleton-toggle)
'''
hook_source = '''
  call skkeleton#config({
    \ 'eggLikeNewline': v:true,
    \ })
  call skkeleton#register_kanatable('rom', {
    \ 'jj': 'escape',
    \ ';': 'henkanPoint',
    \ })
'''

[[plugins]]
repo = 'skanehira/denops-translate.vim'
depends = 'denops.vim'
on_map = ['<Plug>(Translate)', '<Plug>(VTranslate)']
on_cmd = 'Translate'
hook_add = '''
  nmap <C-t> <Plug>(Translate)
  vmap <C-t> <Plug>(VTranslate)
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'
on_cmd = ['Gin', 'GinStatus', 'GinBranch', 'GinDiff']
hook_add = '''
  autocmd MyAutoCmd FileType diff setlocal nolist
  command! GinCommit Gin commit
'''

# [[plugins]]
# repo = 'kat0h/bufpreview.vim'
# on_cmd = 'PreviewMarkdown'

