[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = ['CursorHold']

[[plugins]]
repo = 'vim-skk/skkeleton'
on_source = 'ddc.vim'
on_map = {ic = '<Plug>(skkeleton-toggle)'}
hook_add = '''
  imap <C-Space> <Plug>(skkeleton-toggle)
  cmap <C-Space> <Plug>(skkeleton-toggle)
'''
hook_source = '''
  call skkeleton#config({
    \ 'eggLikeNewline': v:true,
    \ })
  call skkeleton#register_kanatable('rom', {
    \ 'jj': 'escape',
    \ ';': 'henkanPoint',
    \ })
'''

[[plugins]]
repo = 'delphinus/skkeleton_indicator.nvim'
on_source = 'skkeleton'
hook_source = '''
lua << EOF
  vim.api.nvim_exec([[
    hi SkkeletonIndicatorHira guifg=#000000 guibg=#7aa2f7 gui=bold
    hi SkkeletonIndicatorKata guifg=#000000 guibg=#f7768e gui=bold
    hi SkkeletonIndicatorHankata guifg=#000000 guibg=#bb9af7 gui=bold
    hi SkkeletonIndicatorZenkaku guifg=#000000 guibg=#89ddff gui=bold
  ]], false)

  require('skkeleton_indicator').setup {
    alwaysShown = false,
  }
EOF
'''

[[plugins]]
repo = 'skanehira/denops-translate.vim'
depends = 'denops.vim'
on_map = ['<Plug>(Translate)', '<Plug>(VTranslate)']
on_cmd = 'Translate'
hook_add = '''
  nmap <C-t> <Plug>(Translate)
  vmap <C-t> <Plug>(VTranslate)
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'
on_cmd = ['Gin', 'GinStatus', 'GinBranch', 'GinDiff']
hook_add = '''
  autocmd MyAutoCmd FileType diff setlocal nolist
  command! GinCommit Gin commit
'''

