# rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

# markdown
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_cmd = ['MarkdownPreview']
build = 'sh -c "cd app && yarn install"'

[[plugins]]
repo = 'mattn/vim-maketable'
on_cmd = 'MakeTable'
