[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_cmd = 'AsyncRun'
hook_add = '''
  autocmd MyAutoCmd User AsyncRunStart call asyncrun#quickfix_toggle(25, 1)
'''

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_cmd = 'Template'
hook_add = '''
  let g:sonictemplate_vim_template_dir = '$HOME/.config/nvim/template'
'''

[[plugins]]
repo = 'segeljakt/vim-silicon'
on_cmd = 'Silicon'
hook_add = '''
  let g:silicon = {
    \ 'theme': 'Nord',
    \ 'font': 'SauceCodePro Nerd Font',
    \ 'output': '~/Pictures/silicon/silicon-{time:%Y-%m-%d-%H:%M:%S}.png',
    \ }
'''

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'
hook_add = '''
  let g:cursorhold_updatetime = 100
'''

[[plugins]]
repo = 'utubo/vim-auto-hide-cmdline'
