[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'

[[plugins]]
repo = 'akinsho/toggleterm.nvim'
on_cmd = '*ToggleTerm'
hook_add = '''
  nnoremap <silent> <C-p> <Cmd>1ToggleTerm size=80 direction=vertical<CR>
  nnoremap <silent> <C-f> <Cmd>1ToggleTerm direction=float<CR>

  nnoremap <silent> t1    <Cmd>1ToggleTerm direction=float<CR>
  nnoremap <silent> t2    <Cmd>2ToggleTerm direction=float<CR>
  nnoremap <silent> t3    <Cmd>3ToggleTerm direction=float<CR>
  nnoremap <silent> t4    <Cmd>4ToggleTerm direction=float<CR>
  nnoremap <silent> t5    <Cmd>5ToggleTerm direction=float<CR>
'''
[plugins.ftplugin]
toggleterm = '''
  tnoremap <buffer><silent> t1 <Cmd>ToggleTerm<CR><Cmd>1ToggleTerm direction=float<CR>
  tnoremap <buffer><silent> t2 <Cmd>ToggleTerm<CR><Cmd>2ToggleTerm direction=float<CR>
  tnoremap <buffer><silent> t3 <Cmd>ToggleTerm<CR><Cmd>3ToggleTerm direction=float<CR>
  tnoremap <buffer><silent> t4 <Cmd>ToggleTerm<CR><Cmd>4ToggleTerm direction=float<CR>
  tnoremap <buffer><silent> t5 <Cmd>ToggleTerm<CR><Cmd>5ToggleTerm direction=float<CR>

  nnoremap <buffer><silent> t1 <Cmd>ToggleTerm<CR><Cmd>1ToggleTerm direction=float<CR>
  nnoremap <buffer><silent> t2 <Cmd>ToggleTerm<CR><Cmd>2ToggleTerm direction=float<CR>
  nnoremap <buffer><silent> t3 <Cmd>ToggleTerm<CR><Cmd>3ToggleTerm direction=float<CR>
  nnoremap <buffer><silent> t4 <Cmd>ToggleTerm<CR><Cmd>4ToggleTerm direction=float<CR>
  nnoremap <buffer><silent> t5 <Cmd>ToggleTerm<CR><Cmd>5ToggleTerm direction=float<CR>

  tnoremap <buffer><silent> <C-p> <Cmd>ToggleTerm<CR>
  nnoremap <buffer><silent> <C-p> <Cmd>ToggleTerm<CR>
  nnoremap <buffer><silent> <Esc> <Cmd>ToggleTerm<CR>
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_cmd = 'AsyncRun'
hook_add = '''
  autocmd MyAutoCmd User AsyncRunStart call asyncrun#quickfix_toggle(20, 1)
'''

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_cmd = 'Template'
hook_add = '''
  let g:sonictemplate_vim_template_dir = '$HOME/.config/nvim/template'
'''

[[plugins]]
repo = 'mattn/vim-maketable'
on_cmd = 'MakeTable'

[[plugins]]
repo = 'lambdalisue/vim-backslash'
on_ft = 'vim'

[[plugins]]
repo = 'segeljakt/vim-silicon'
on_cmd = 'Silicon'
hook_add = '''
  let g:silicon = {}
  let g:silicon['theme'] = 'Nord'
  let g:silicon['font'] = 'SauceCodePro Nerd Font'
  let g:silicon['output'] = '~/Pictures/silicon/silicon-{time:%Y-%m-%d-%H:%M:%S}.png'
'''

[[plugins]]
repo = 'tpope/vim-surround'
on_event = ['CursorHold']
on_map = ['S', 'cs', 'ds']

[[plugins]]
repo = 'tpope/vim-commentary'
on_event = ['CursorHold']
on_map = ['gc', 'gcc']

[[plugins]]
repo = 'z0mbix/vim-shfmt'
on_ft = 'sh'
hook_add = '''
  let g:shfmt_fmt_on_save = 1
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_cmd = ['MarkdownPreview']
build = 'sh -c "cd app && yarn install"'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_cmd = ['ColorizerToggle']

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
on_ft = ['rust', 'haskell']
hook_source = '''
lua << EOF
  require('indent_blankline').setup {
    show_and_of_line = true,
  }
EOF
'''

